# Generated by Django 4.1.1 on 2022-12-03 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_yorummodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yorummodel',
            old_name='olusumtarih',
            new_name='olusumtarih',
        ),
        migrations.RemoveField(
            model_name='yorummodel',
            name='guncellemetarihi',
        ),
        migrations.AddField(
            model_name='yorummodel',
            name='guncellemetarihi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yorummodel',
            name='yorum',
            field=models.TextField(default=datetime.datetime(2022, 12, 3, 18, 47, 55, 775681, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
