# Generated by Django 4.1.1 on 2022-12-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_olusumtarihi_yorummodel_olusumtarih_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorummodel',
            name='guncellemetarihi',
        ),
        migrations.AddField(
            model_name='yorummodel',
            name='guncellemetarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
