# Generated by Django 4.1.1 on 2023-01-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_yorummodel_guncellemetarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('name_surname', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('olusumtarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Iletisim',
                'verbose_name_plural': 'iletişim',
                'db_table': 'iletisim',
            },
        ),
    ]
